<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Automatic variance detection (Section 23) — one row per compared field,
 * generated by AuditService::detectVariances() when the Audit screen loads.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('audit_variances', function (Blueprint $table) {
            $table->id();
            $table->foreignId('audit_record_id')->constrained('audit_records')->cascadeOnDelete();
            $table->string('field_key', 60); // product, sku, quantity, vendor, tenant, start_date, end_date, cost
            $table->string('label', 150);
            $table->string('approved_value', 255)->nullable();
            $table->string('actual_value', 255)->nullable();
            $table->boolean('is_mismatch')->default(false);
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('audit_variances');
    }
};
